### ISSUE TITLE
Make project work with Docker and Docker-compose

### ISSUE THREAD

**Issue by EdisonArango** [altixco/altixco.github.io#2]
See:
- https://github.com/altixco/django-postgres-dokku

**Comment by EdisonArango** [comment]
Any update on this?.

**Comment by jdrb2098** [comment]
Not jet we lost the morning because of the internet issues. I pretend to
work on th Mac in the office cause there is installed Docker. im installing
it on my old pc and trying to learn how to do it - did u have some
recommendation of were I can find Docker information?

**Comment by EdisonArango** [comment]
Yes, it's in the Knowledge site: 
https://knowledge.altix.co/stack/docker.html

Basically the official docker docs is the best starting point, and there is a lot of resources out there about Docker, most developers use it therefore it's not hard to find solutions.

**Comment by jdrb2098** [comment]
Hi Edison, i have a truble cause i don't know the requirements for the dockerfile. to be more  spesificl what should i put in de "from". else if there is a way to know that from the file?

**Comment by EdisonArango** [comment]
@Camilandia20 This is done, but please review the result of the pull request that Juan did:
https://github.com/altixco/altixco.github.io/pull/6
